language: php

sudo: false

php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

notifications:
  on_success: never
  on_failure: always

git:
  depth: 1

install:
  - curl --version
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]] ; then
        ./vendor/bin/phpunit --coverage-clover=coverage.xml
    else
        ./vendor/bin/phpunit
    fi
  - ./vendor/bin/phpcs --standard=PSR2 -snp --encoding=utf-8 src/ --report-width=150

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
